import { ICalendarSettings } from '../models/ICalendarSettings';
import { IEvent } from '../models/IEvent';
import { ICreateEventPayload, PublishingChannel } from '../../../services/GraphService';
import { WebPartContext } from '@microsoft/sp-webpart-base';

export interface IUpcomingEventsWebPartProps {
  bannerTitle: string;
  bannerDescription: string;
  showEventCount: boolean;
  calendarPosition: 'left' | 'right';
  enableNigerianHolidays: boolean;
  holidayBadgeText: string;
  holidayBadgeColor: string;
  holidayIconType: string;
  autoRefreshHolidays: boolean;
  events: IEvent[];
  eventsToShow: number;
  showPastEvents: boolean;
  sortOrder: 'dateAsc' | 'dateDesc' | 'custom';
  cardLayout: 'horizontal' | 'vertical';
  showEventImages: boolean;
  calendarSettings: ICalendarSettings;
  showDateMetadata: boolean;
  showTimeMetadata: boolean;
  showLocationMetadata: boolean;
  clientId: string;
  tenantId: string;
  objectId: string;
  authorizedEditors: string;
  siteId: string;
  listId: string;
  teamId: string;
  channelId: string;
  groupId: string;
  vivaCommunityId: string;
  emailRecipients: string;
  isEditor: boolean;
  currentUserEmail: string;
  context: WebPartContext;
  onEventsChange?: (events: IEvent[]) => void;
  onCreateEvent?: (payload: ICreateEventPayload, channels: PublishingChannel[]) => Promise<void>;
}
